# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('items', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField()),
                ('vk_token', models.CharField(max_length=255)),
                ('black_list', models.TextField(blank=True)),
                ('groups', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Groups')),
            ],
        ),
    ]
